/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AptekaInternetowa.java;

import AptekaInternetowa.models.Lek;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import AptekaInternetowa.models.Uzytkownik;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;

/**
 *
 * @author Wojtek
 */
public class PanelZamowieniaKlienta extends javax.swing.JFrame {

    /**
     * Creates new form PanelZamowienia
     */
    ArrayList<Lek> tabLekiDoZaplatyDB = (new DatabaseLayer()).getLekidoZaplaty();
    DatabaseSingleton db = null;
    ArrayList<Lek> tempLekiDoZaplaty = new ArrayList<>();
    int Selectedrow = 0;
    float kosztBezVatu = 0; 
    float kosztzVATem = 0;
    float tempKosztBezVATu = 0;    
    float tempKosztZVATem = 0;    
    

    public PanelZamowieniaKlienta() {
        
    try {
            initComponents();
            db = new DatabaseSingleton();
            
            ArrayList<Lek> tablicaLekowzDB = db.pokazLekizDB();
            tabLekiDoZaplatyDB = tablicaLekowzDB;
            jLabel2.setText(Uzytkownik.Nazwa);
            jTable_LekiwPromocji.setModel(new TableModel_LekiWPromocji());
            jTable_NoweLeki.setModel(new TableModel_NoweLeki());
            jTable_LekiDoZaplaty.setModel(new TableModel_LekiDoZaplaty());
            
            jTable_NoweLeki.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    Selectedrow = jTable_NoweLeki.getSelectedRow()+1;
                }
            });
            jTable_NoweLeki.getModel().addTableModelListener(new TableModelListener() {
                
                @Override
                public void tableChanged(TableModelEvent e) {
                    //    jTable_LekiDoZaplaty.setModel(new TableModel_LekiWPromocji());
                    
                    Integer id = tabLekiDoZaplatyDB.get(Selectedrow).getId();
                    String nazwa = tabLekiDoZaplatyDB.get(Selectedrow).getNazwa();
                    String producent = tabLekiDoZaplatyDB.get(Selectedrow).getProducent();
                    Float cena = tabLekiDoZaplatyDB.get(Selectedrow).getCena();
                    Integer ilosc = tabLekiDoZaplatyDB.get(Selectedrow).getSztuk();
                    
                    Lek lek = new Lek(Selectedrow, nazwa, producent, cena, ilosc);
                    
                    
                    tempLekiDoZaplaty.add(lek);
                    dodajDoZaplaty(cena);
                    dodajDoZaplatyzVATem(cena);
                    lacznieDoZaplacenia();
                    
                    
                    TableModel_LekiDoZaplaty model = new TableModel_LekiDoZaplaty();
                    model.tabLekiDoZaplaty = tempLekiDoZaplaty;
                    jTable_LekiDoZaplaty.setModel(model);
                }
                
            });
            jTable_LekiwPromocji.getModel().addTableModelListener((TableModelEvent e) -> {
                
                Lek lek = new Lek(e.getFirstRow(), "TABELA_2", "TEST_2", 14, 5);
                
                tabLekiDoZaplatyDB.clear();
                tabLekiDoZaplatyDB.add(lek);

                TableModel_LekiDoZaplaty model = new TableModel_LekiDoZaplaty();
                model.tabLekiDoZaplaty = tabLekiDoZaplatyDB;
                jTable_LekiDoZaplaty.setModel(model);
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_NoweLeki = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_LekiwPromocji = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_LekiDoZaplaty = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Wyloguj_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        doZaplacenia_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        WyslijZamowienie_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        doZaplaceniazVatem_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apteka Internetowa - Panel Zamówienia");

        jLabel1.setText("Jesteś zalogowany jako: ");

        jLabel5.setText("Ofiarowane lekii:");

        jTable_NoweLeki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nazwa", "Producent", "Cena"
            }
        ));
        jTable_NoweLeki.setEditingRow(0);
        jScrollPane3.setViewportView(jTable_NoweLeki);

        jTabbedPane2.addTab("Nowe", jScrollPane3);

        jTable_LekiwPromocji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nazwa", "Producent", "Cena"
            }
        ));
        jScrollPane2.setViewportView(jTable_LekiwPromocji);

        jTabbedPane2.addTab("W promocji", jScrollPane2);

        jTable_LekiDoZaplaty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nazwa", "Producent", "Cena"
            }
        ));
        jScrollPane4.setViewportView(jTable_LekiDoZaplaty);

        jLabel3.setText("Do zapłaty:");

        jLabel2.setText("jLabel2");

        Wyloguj_button.setText("Wyloguj");
        Wyloguj_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wyloguj_buttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Paragon:");

        jLabel7.setText("Imię:");

        jLabel8.setText("Nazwisko:");

        jLabel12.setText("Ulica:");

        jTextField1.setToolTipText("");

        jLabel10.setText("Nr bloku:");

        jLabel11.setText("Nr mieszkania:");

        jLabel13.setText("Kod pocztowy:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        doZaplacenia_label.setText("..............");

        jLabel4.setText("Razem do zapłaty:");

        WyslijZamowienie_button.setText("Wyślij zamówienie");
        WyslijZamowienie_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyslijZamowienie_buttonActionPerformed(evt);
            }
        });

        jLabel9.setText("+ 18% VAT = ");

        doZaplaceniazVatem_label.setText("..........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WyslijZamowienie_button)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(doZaplacenia_label)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(doZaplaceniazVatem_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Wyloguj_button)
                        .addGap(11, 11, 11))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Wyloguj_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(doZaplacenia_label)
                    .addComponent(jLabel9)
                    .addComponent(doZaplaceniazVatem_label))
                .addGap(18, 18, 18)
                .addComponent(WyslijZamowienie_button)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Wyloguj_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wyloguj_buttonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_Wyloguj_buttonActionPerformed

    private void WyslijZamowienie_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyslijZamowienie_buttonActionPerformed
        if(jTextField1.getText().isEmpty() || 
           jTextField2.getText().isEmpty() ||
           jTextField3.getText().isEmpty() ||
           jTextField4.getText().isEmpty() ||
           jTextField5.getText().isEmpty() ||
           jTextField6.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Musisz uzupełnić dane kontaktowe, żeby zamówienie było zrealizowane.","Stan zamówienia.",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Zamówienie jest w trakcie realizacji. \nDziękujemy za skorzystanie z naszej firmy.","Stan zamówienia.",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_WyslijZamowienie_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelZamowieniaKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PanelZamowieniaKlienta().setVisible(true);
                
              
              
            }
        });
    }

    public JTable getJTable4() {
        return jTable_LekiDoZaplaty;
    }
    
    public void lacznieDoZaplacenia()
    {
        tempKosztBezVATu += kosztBezVatu;
        tempKosztZVATem += kosztzVATem;
        doZaplacenia_label.setText(Float.toString(tempKosztBezVATu));
        
        String wynik = Float.toString(tempKosztZVATem);
        doZaplaceniazVatem_label.setText( wynik );
        
    }
    
    void dodajDoZaplaty(float cena)
    {
      kosztBezVatu = cena;  
    }
    
    void dodajDoZaplatyzVATem(float cena)
    {
      kosztzVATem = (float) (cena + (0.018 * cena));  
    }
    
   
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Wyloguj_button;
    private javax.swing.JButton WyslijZamowienie_button;
    private javax.swing.JLabel doZaplacenia_label;
    private javax.swing.JLabel doZaplaceniazVatem_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable_LekiDoZaplaty;
    private javax.swing.JTable jTable_LekiwPromocji;
    private javax.swing.JTable jTable_NoweLeki;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
